#! /bin/sh
NAME="Chris Ostrum"
EMAIL="chris.ostrum@gmail.com"

# Install programs
echo 'Installing programs...'
sudo apt-get install vim
sudo apt-get install exuberant-ctags
sudo apt-get install git
sudo apt-get install cmake
echo 'Programs installed.'

# Configure them
echo 'Configuring git...'
git config --global --replace-all user.name $NAME
git config --global --replace-all user.email $EMAIL
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=3600'
echo 'Completed git.'

if [ -f ".vimrc" ]; then
    echo 'Update vim...'
    cp .vimrc ~/
    cp .vimrc.bundles ~/
    cd ~/ && vim +BundleInstall! +BundleClean +q
    echo 'Completed vim update.'
fi
