#! /bin/sh
NAME=""
EMAIL=""

# Install programs
echo 'Installing programs...'
sudo apt-get install vim
sudo apt-get install exuberant-ctags
sudo apt-get install git
sudo apt-get install cmake
echo 'Programs installed.'

# Configure them
echo 'Configuring git...'
git config --global --replace-all user.name $NAME
git config --global --replace-all user.email $EMAIL
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=3600'
echo 'Completed git.'

mkdir ~/dev
cd ~/dev

git clone https://github.com/sigurdga/gnome-terminal-colors-solarized.git
gnome-terminal-colors-solarized/install.sh

git clone https://github.com/seebi/dircolors-solarized.git
