#! /bin/sh
NAME="Chris Ostrum"
EMAIL="chris.ostrum@gmail.com"

# Install programs
echo 'Installing programs...'
sudo apt-get install vim
sudo apt-get install exuberant-ctags
sudo apt-get install git
echo 'Programs installed.'

# Configure them
echo 'Configuring git...'
git config --global user.name $NAME
git config --global user.email $EMAIL
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=3600'
echo 'Completed git.'
